name = "TypeParameterAccessors"
uuid = "7e5a90cf-f82e-492e-a09b-e3e26432c138"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.3.11"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
StridedViews = "4db3bf67-4bd7-4b4e-b153-31dc3fb37143"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[extensions]
TypeParameterAccessorsAMDGPUExt = "AMDGPU"
TypeParameterAccessorsCUDAExt = "CUDA"
TypeParameterAccessorsFillArraysExt = "FillArrays"
TypeParameterAccessorsJLArraysExt = "JLArrays"
TypeParameterAccessorsMetalExt = "Metal"
TypeParameterAccessorsStridedViewsExt = "StridedViews"
TypeParameterAccessorsoneAPIExt = "oneAPI"

[compat]
AMDGPU = "0, 1, 2"
CUDA = "3, 4, 5"
FillArrays = "1.13"
JLArrays = "0.1, 0.2, 0.3"
LinearAlgebra = "1.10"
Metal = "0, 1"
SimpleTraits = "0.9.4"
StridedViews = "0.3.2, 0.4"
julia = "1.10"
oneAPI = "0, 1, 2"
